spring:
  application:
    name: management-prototype

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hostelmgmt?useSSL=false&serverTimezone=UTC
    username: root
    password: Hanuman@97
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
